title: Irfan Ahamed K
description: Law Student | Legal Research | Litigation Support
theme: minima
author: Irfan Ahamed K

header_pages:
  - about.md
  - education.md
  - experience.md
  - skills.md
  - contact.md
